import type { InputFactors } from './mlSimulator';

export interface MetrologyInstrument extends InputFactors {
  id: string;
}

export const INITIAL_INSTRUMENTS: MetrologyInstrument[] = [
  {
    id: 'INST-001',
    name: 'Thermomètre de Précision PT100',
    serialNumber: 'SN-PT100-8842',
    type: 'Thermomètre',
    manufacturer: 'Fluke Calibration',
    range: '-50°C à +250°C',
    resolution: '0.01°C',
    tolerance: 0.05,
    toleranceUnit: '°C',
    commissionDate: '2022-04-15',
    driftRate: 2.1,
    useCondition: 'normal',
    useFrequency: 85,
    envTemp: 4,
    envHumidity: 3,
    envVibration: 2,
    criticality: 'critical',
    complianceHistory: 98,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.25,
    currentInterval: 12
  },
  {
    id: 'INST-002',
    name: 'Manomètre Digital HP',
    serialNumber: 'SN-MAND-3109',
    type: 'Manomètre',
    manufacturer: 'WIKA',
    range: '0 à 400 bar',
    resolution: '0.1 bar',
    tolerance: 0.5,
    toleranceUnit: 'bar',
    commissionDate: '2023-01-20',
    driftRate: 12.8,
    useCondition: 'severe',
    useFrequency: 340,
    envTemp: 8,
    envHumidity: 7,
    envVibration: 9,
    criticality: 'security',
    complianceHistory: 85,
    lastCalibResult: 'warning',
    uncertaintyRatio: 0.72,
    currentInterval: 12
  },
  {
    id: 'INST-003',
    name: 'Pied à coulisse électronique IP67',
    serialNumber: 'SN-PAC-7711',
    type: 'Pied à coulisse',
    manufacturer: 'Mitutoyo',
    range: '0 à 200 mm',
    resolution: '0.01 mm',
    tolerance: 0.02,
    toleranceUnit: 'mm',
    commissionDate: '2024-06-10',
    driftRate: 4.5,
    useCondition: 'normal',
    useFrequency: 150,
    envTemp: 3,
    envHumidity: 4,
    envVibration: 3,
    criticality: 'important',
    complianceHistory: 95,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.38,
    currentInterval: 12
  },
  {
    id: 'INST-004',
    name: 'Balance de Précision Analytique',
    serialNumber: 'SN-BAL-9902',
    type: 'Balance',
    manufacturer: 'Mettler Toledo',
    range: '0 à 220 g',
    resolution: '0.1 mg',
    tolerance: 0.5,
    toleranceUnit: 'mg',
    commissionDate: '2021-09-05',
    driftRate: 1.2,
    useCondition: 'light',
    useFrequency: 45,
    envTemp: 2,
    envHumidity: 2,
    envVibration: 1,
    criticality: 'standard',
    complianceHistory: 100,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.15,
    currentInterval: 12
  },
  {
    id: 'INST-005',
    name: 'Multimètre de Table 6½ Chiffres',
    serialNumber: 'SN-MULT-5021',
    type: 'Multimètre',
    manufacturer: 'Keysight Technologies',
    range: '0 à 1000 V',
    resolution: '1 µV',
    tolerance: 0.005,
    toleranceUnit: '%',
    commissionDate: '2022-11-30',
    driftRate: 3.2,
    useCondition: 'light',
    useFrequency: 220,
    envTemp: 3,
    envHumidity: 3,
    envVibration: 2,
    criticality: 'important',
    complianceHistory: 97,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.22,
    currentInterval: 12
  },
  {
    id: 'INST-006',
    name: 'Chronomètre Industriel Digital',
    serialNumber: 'SN-CHRO-4410',
    type: 'Chronomètre',
    manufacturer: 'Hanhart',
    range: '0 à 10 heures',
    resolution: '0.01 s',
    tolerance: 0.1,
    toleranceUnit: 's',
    commissionDate: '2023-08-14',
    driftRate: 16.5,
    useCondition: 'severe',
    useFrequency: 410,
    envTemp: 7,
    envHumidity: 6,
    envVibration: 6,
    criticality: 'critical',
    complianceHistory: 78,
    lastCalibResult: 'out_of_tolerance',
    uncertaintyRatio: 1.15,
    currentInterval: 12
  },
  {
    id: 'INST-007',
    name: 'Sonomètre de Classe 1',
    serialNumber: 'SN-SONO-0199',
    type: 'Sonomètre',
    manufacturer: 'Brüel & Kjær',
    range: '20 à 140 dB',
    resolution: '0.1 dB',
    tolerance: 0.7,
    toleranceUnit: 'dB',
    commissionDate: '2022-07-22',
    driftRate: 5.8,
    useCondition: 'normal',
    useFrequency: 60,
    envTemp: 4,
    envHumidity: 5,
    envVibration: 3,
    criticality: 'important',
    complianceHistory: 92,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.45,
    currentInterval: 12
  },
  {
    id: 'INST-008',
    name: 'Luxmètre Professionnel',
    serialNumber: 'SN-LUX-3305',
    type: 'Luxmètre',
    manufacturer: 'Chauvin Arnoux',
    range: '0.1 à 200000 lux',
    resolution: '0.1 lux',
    tolerance: 3.0,
    toleranceUnit: '%',
    commissionDate: '2023-05-18',
    driftRate: 8.9,
    useCondition: 'normal',
    useFrequency: 110,
    envTemp: 5,
    envHumidity: 5,
    envVibration: 4,
    criticality: 'standard',
    complianceHistory: 88,
    lastCalibResult: 'warning',
    uncertaintyRatio: 0.58,
    currentInterval: 12
  },
  {
    id: 'INST-009',
    name: 'Manomètre à Tube Bourdon',
    serialNumber: 'SN-MANB-2291',
    type: 'Manomètre',
    manufacturer: 'WIKA',
    range: '0 à 25 bar',
    resolution: '0.5 bar',
    tolerance: 1.0,
    toleranceUnit: '%',
    commissionDate: '2021-02-10',
    driftRate: 24.2,
    useCondition: 'severe',
    useFrequency: 490,
    envTemp: 9,
    envHumidity: 8,
    envVibration: 8,
    criticality: 'security',
    complianceHistory: 65,
    lastCalibResult: 'out_of_tolerance',
    uncertaintyRatio: 1.45,
    currentInterval: 12
  },
  {
    id: 'INST-010',
    name: 'Thermomètre Infrarouge Optique',
    serialNumber: 'SN-TIR-6543',
    type: 'Thermomètre',
    manufacturer: 'Raytek',
    range: '-30°C à +900°C',
    resolution: '0.1°C',
    tolerance: 1.5,
    toleranceUnit: '°C',
    commissionDate: '2023-10-05',
    driftRate: 7.1,
    useCondition: 'normal',
    useFrequency: 180,
    envTemp: 6,
    envHumidity: 5,
    envVibration: 5,
    criticality: 'important',
    complianceHistory: 90,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.52,
    currentInterval: 12
  },
  {
    id: 'INST-011',
    name: 'Balance Industrielle de Plateforme',
    serialNumber: 'SN-BALI-1209',
    type: 'Balance',
    manufacturer: 'Sartorius',
    range: '0 à 150 kg',
    resolution: '5 g',
    tolerance: 15,
    toleranceUnit: 'g',
    commissionDate: '2020-05-12',
    driftRate: 6.4,
    useCondition: 'severe',
    useFrequency: 290,
    envTemp: 8,
    envHumidity: 7,
    envVibration: 7,
    criticality: 'critical',
    complianceHistory: 91,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.61,
    currentInterval: 12
  },
  {
    id: 'INST-012',
    name: 'Pied à coulisse mécanique Vernier',
    serialNumber: 'SN-PACM-5520',
    type: 'Pied à coulisse',
    manufacturer: 'Mitutoyo',
    range: '0 à 150 mm',
    resolution: '0.02 mm',
    tolerance: 0.03,
    toleranceUnit: 'mm',
    commissionDate: '2019-11-20',
    driftRate: 1.8,
    useCondition: 'light',
    useFrequency: 50,
    envTemp: 3,
    envHumidity: 3,
    envVibration: 2,
    criticality: 'standard',
    complianceHistory: 99,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.20,
    currentInterval: 12
  },
  {
    id: 'INST-013',
    name: 'Calibrateur de Processus Multifonction',
    serialNumber: 'SN-CALP-8033',
    type: 'Multimètre',
    manufacturer: 'Fluke Calibration',
    range: '0 à 24 mA / 0 à 30 V',
    resolution: '1 µA / 1 mV',
    tolerance: 0.01,
    toleranceUnit: '%',
    commissionDate: '2023-03-25',
    driftRate: 2.8,
    useCondition: 'light',
    useFrequency: 95,
    envTemp: 3,
    envHumidity: 2,
    envVibration: 2,
    criticality: 'critical',
    complianceHistory: 98,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.30,
    currentInterval: 12
  },
  {
    id: 'INST-014',
    name: 'Micromètre Extérieur de Précision',
    serialNumber: 'SN-MIC-9104',
    type: 'Pied à coulisse', // Treated as caliper type in grouping
    manufacturer: 'Mitutoyo',
    range: '0 à 25 mm',
    resolution: '0.001 mm',
    tolerance: 0.004,
    toleranceUnit: 'mm',
    commissionDate: '2022-09-12',
    driftRate: 0.9,
    useCondition: 'light',
    useFrequency: 70,
    envTemp: 2,
    envHumidity: 3,
    envVibration: 1,
    criticality: 'critical',
    complianceHistory: 100,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.12,
    currentInterval: 12
  },
  {
    id: 'INST-015',
    name: 'Capteur de Température Température/Humidité',
    serialNumber: 'SN-THS-0238',
    type: 'Thermomètre',
    manufacturer: 'Testo',
    range: '-20°C à +70°C / 0 à 100% HR',
    resolution: '0.1°C / 0.1%',
    tolerance: 0.5,
    toleranceUnit: '°C',
    commissionDate: '2024-02-18',
    driftRate: 5.1,
    useCondition: 'normal',
    useFrequency: 450, // continuous logger
    envTemp: 5,
    envHumidity: 6,
    envVibration: 2,
    criticality: 'important',
    complianceHistory: 94,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.42,
    currentInterval: 12
  },
  {
    id: 'INST-016',
    name: 'Voltmètre Numérique Haute Précision',
    serialNumber: 'SN-VOLT-7729',
    type: 'Multimètre',
    manufacturer: 'Keithley',
    range: '0 à 100 V',
    resolution: '0.1 µV',
    tolerance: 0.002,
    toleranceUnit: '%',
    commissionDate: '2021-07-30',
    driftRate: 1.5,
    useCondition: 'light',
    useFrequency: 120,
    envTemp: 2,
    envHumidity: 2,
    envVibration: 1,
    criticality: 'security',
    complianceHistory: 99,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.18,
    currentInterval: 12
  },
  {
    id: 'INST-017',
    name: 'Indicateur de Pression Différentielle',
    serialNumber: 'SN-PRED-3401',
    type: 'Manomètre',
    manufacturer: 'Dwyer Instruments',
    range: '0 à 10 kPa',
    resolution: '0.01 kPa',
    tolerance: 0.5,
    toleranceUnit: '%',
    commissionDate: '2023-11-15',
    driftRate: 11.2,
    useCondition: 'normal',
    useFrequency: 210,
    envTemp: 6,
    envHumidity: 6,
    envVibration: 4,
    criticality: 'important',
    complianceHistory: 87,
    lastCalibResult: 'warning',
    uncertaintyRatio: 0.65,
    currentInterval: 12
  },
  {
    id: 'INST-018',
    name: 'Chronomètre Numérique Double Quartz',
    serialNumber: 'SN-CHRD-8844',
    type: 'Chronomètre',
    manufacturer: 'Seiko',
    range: '0 à 24 heures',
    resolution: '0.001 s',
    tolerance: 0.02,
    toleranceUnit: 's',
    commissionDate: '2022-01-25',
    driftRate: 2.5,
    useCondition: 'light',
    useFrequency: 30,
    envTemp: 2,
    envHumidity: 2,
    envVibration: 1,
    criticality: 'standard',
    complianceHistory: 100,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.21,
    currentInterval: 12
  },
  {
    id: 'INST-019',
    name: 'Sonomètre Intégrateur de Chantier',
    serialNumber: 'SN-SONC-4521',
    type: 'Sonomètre',
    manufacturer: 'Pulsar Instruments',
    range: '30 à 130 dB',
    resolution: '0.1 dB',
    tolerance: 1.0,
    toleranceUnit: 'dB',
    commissionDate: '2023-04-10',
    driftRate: 14.1,
    useCondition: 'severe',
    useFrequency: 260,
    envTemp: 8,
    envHumidity: 8,
    envVibration: 7,
    criticality: 'important',
    complianceHistory: 82,
    lastCalibResult: 'warning',
    uncertaintyRatio: 0.88,
    currentInterval: 12
  },
  {
    id: 'INST-020',
    name: 'Luxmètre Data Logger IP54',
    serialNumber: 'SN-LUXD-6712',
    type: 'Luxmètre',
    manufacturer: 'Extech',
    range: '0 à 400000 lux',
    resolution: '0.01 lux',
    tolerance: 4.0,
    toleranceUnit: '%',
    commissionDate: '2024-01-08',
    driftRate: 4.2,
    useCondition: 'normal',
    useFrequency: 140,
    envTemp: 4,
    envHumidity: 4,
    envVibration: 3,
    criticality: 'standard',
    complianceHistory: 96,
    lastCalibResult: 'conforming',
    uncertaintyRatio: 0.35,
    currentInterval: 12
  }
];
